from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table
from reportlab.lib.styles import getSampleStyleSheet
import pandas as pd
import os

def generate_pdf():
    os.makedirs("reports", exist_ok=True)
    pdf_path = "reports/APK_Security_Analysis_Report.pdf"
    doc = SimpleDocTemplate(pdf_path, pagesize=A4)
    styles = getSampleStyleSheet()
    content = []

    content.append(Paragraph("<b>APK Security Analysis Report</b>", styles["Title"]))
    content.append(Spacer(1, 20))
    content.append(Paragraph("This report summarizes the automated analysis of APK files using ML-based classification and unsupervised clustering to detect security risks and behavioral patterns.", styles["BodyText"]))
    content.append(Spacer(1, 15))

    if os.path.exists("output/results.csv"):
        df_class = pd.read_csv("output/results.csv")
        content.append(Paragraph("<b>Classification Summary</b>", styles["Heading2"]))
        content.append(Spacer(1, 8))
        data = [df_class.columns.tolist()] + df_class.values.tolist()
        content.append(Table(data))
        content.append(Spacer(1, 20))

    if os.path.exists("output/cluster_results.csv"):
        df_cluster = pd.read_csv("output/cluster_results.csv")
        content.append(Paragraph("<b>Cluster Analysis Summary</b>", styles["Heading2"]))
        content.append(Spacer(1, 8))
        data = [df_cluster.columns.tolist()] + df_cluster.values.tolist()
        content.append(Table(data))
        content.append(Spacer(1, 20))

    if os.path.exists("output/clusters.png"):
        content.append(Paragraph("<b>Cluster Visualization</b>", styles["Heading2"]))
        content.append(Spacer(1, 8))
        content.append(Image("output/clusters.png", width=400, height=300))
        content.append(Spacer(1, 20))

    content.append(Paragraph("Generated by APK Security Toolkit", styles["Italic"]))
    doc.build(content)
    print(f" PDF report saved at: {pdf_path}")

if __name__ == "__main__":
    generate_pdf()
